name: PipeLine with GitHub Actions

on: push

jobs:
  detox_automation:
    runs-on: macOS-latest
    steps:
    - name: Setup Git Environment
      uses: actions/checkout@v2
    - name: Specify node version
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Use specific Java version for sdkmanager to work
      uses: joschi/setup-jdk@v1
      with:
        java-version: 'openjdk8'
        architecture: 'x64'
    - name: Download Android Emulator Image
      run: |
        echo y | sudo $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-29;google_apis;x86" > /dev/null
        $ANDROID_HOME/tools/bin/avdmanager -s create avd -n Pixel_2_API_29 --device "pixel_xl" -k "system-images;android-29;google_apis;x86" -b "x86" -c 2G -d 7 -f  
    - name: Start Android Emulator
      run: |
        filepath=`pwd`
        echo $filepath
        cd .android/avd/
        ls -ls
        cd
        cat .android/avd/Pixel_2_API_29.avd/config.ini
        echo "PlayStore.enabled=false\nabi.type=x86\navd.ini.encoding=UTF-8\nhw.accelerometer=yes\nhw.audioInput=yes\nhw.battery=yes\nhw.cpu.arch=x86\nhw.dPad=no\nhw.device.manufacturer=Google\nhw.device.name=Nexus 4\nhw.gps=yes\nhw.lcd.density=420\nhw.lcd.height=1920\nhw.lcd.width=1080\nhw.mainKeys=no\nhw.sdCard=yes\nhw.sensors.orientation=yes\nhw.sensors.proximity=yes\nhw.trackBall=no\nimage.sysdir.1=system-images/android-29/google_apis/x86/\nsdcard.size=512G\ntag.display=Google APIs\ntag.id=google_apis" > .android/avd/Pixel_2_API_29.avd/config.ini
        cat .android/avd/Pixel_2_API_29.avd/config.ini
        cd $filepath

#  - nohup $ANDROID_HOME/emulator/emulator -avd Pixel_2_API_29 -no-boot-anim -no-audio -verbose &
 