name: PipeLine with GitHub Actions

on: push

jobs:
  detox_automation:
    runs-on: macOS-latest
    steps:
    - name: Setup Git Environment
      uses: actions/checkout@v2
    - name: Specify node version
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Use specific Java version for sdkmanager to work
      uses: joschi/setup-jdk@v1
      with:
        java-version: 'openjdk8'
        architecture: 'x64'
    - name: Download Android Emulator Image
      run: |
        pwd
        cd
        ls -la
        echo y | sudo $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-29;google_apis;x86" > /dev/null
        $ANDROID_HOME/tools/bin/avdmanager -s create avd -n Pixel_2_API_29 --device "pixel_xl" -k "system-images;android-29;google_apis;x86" -b "x86" -c 2G -d 7 -f  
        cat .android/avd/emu.avd/config.ini
    - name: Start Android Emulator
      run: nohup $ANDROID_HOME/emulator/emulator -avd Pixel_2_API_29 -no-boot-anim -no-audio -verbose &
